[tool.poetry]
name = "entity-matchers"
version = "0.1.0"
description = ""
authors = ["Andrei Olar <andrei.olar@dpgmedia.nl>"]
readme = "README.md"
packages = [{include = "matchescu", from="src"}]

[tool.poetry.dependencies]
python = "^3.11"
certifi = "^2023.7.22"
pandas = "^2.0.3"
matchescu-abstractions = {path = "../abstractions"}


[tool.poetry.group.dev.dependencies]
pytest = "^7.2.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
