[tool.poetry]
name = "entity-matchers"
version = "0.1.0"
description = ""
authors = ["Andrei Olar <andrei.olar@dpgmedia.nl>"]
readme = "README.md"
packages = [{include = "matchescu", from="src"}]

[tool.poetry.dependencies]
python = "^3.12"
certifi = "^2023.7.22"
pandas = "^2.2.3"
ppjoin = {git = "https://github.com/usc-isi-i2/ppjoin.git", rev = "0.2.0"}
polars = "^1.8.2"
jellyfish = "^1.1.0"
numpy = "^2.1.1"
matchescu-base = {path = "../base"}


[tool.poetry.group.dev.dependencies]
pytest = "^8.3.3"
notebook = "^7.2.2"
plotly = "^5.24.1"
black = "^24.8.0"


[tool.poetry.group.development.dependencies]
jupyterlab = "^4.2.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
